services:

  app:
    build: .
    container_name: hr-board-app
    working_dir: /app/src
    env_file:  # Load environment variables from .env
      - src/.env
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: flask run
    depends_on:
      - db
    environment:
      - DATABASE_PATH=postgresql://postgres:1234@db:5432/employee


  db:
    image: postgres:16  
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: employee
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "db"]
      interval: 10s
      timeout: 5s
      retries: 5



volumes:
  postgres-data:
