services:

  app:
    build: .
    container_name: hr-board-app
    working_dir: /app/src
    env_file:  # Load environment variables from .env
      - src/.env
    volumes:
      - .:/app
    networks:
      - shared_net
    ports:
      - "5002:5002"
    command: flask run
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_PATH=postgresql://postgres:1234@db:5432/employee


  db:
    image: docker.arvancloud.ir/postgres:16  
    container_name: db
    ports:
      - "5433:5432" 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: employee
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5



networks:
  shared_net:
    name: shared_net
    driver: bridge
    external: true  


volumes:
  postgres-data:
