"""Add filetype column to Name model

Revision ID: d80e370dcff2
Revises: 
Create Date: 2024-08-31 15:50:47.556246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80e370dcff2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('name', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filetype', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('name', schema=None) as batch_op:
        batch_op.drop_column('filetype')

    # ### end Alembic commands ###
